puts "Seeding users..."
nick = User.create!(username: "ndtelep", email: "ndtelep@gmail.com", password: "goyankees")
allyson = User.create!(username: "allonsy", email:"allonslylotz@gmail.com", password: "gocardinals")
nathan = User.create!(username: "dragoncaker", email: "dragoncaker@gmail.com", password: "goniners")
emily = User.create!(username: "apple.shampoo", email: "apple@gmail.com", password: "goavs")
jeff = User.create!(username: "pretzels", email: "pretzels@gmail.com", password: "gopackgo")

puts "Seeding items..."
i1 = Item.create!(user_id: nick.id,
    team: "Adirondack Flames",
    sport: "ice hockey",
    category: "jersey",
    era: "2014-15",
    brand: "CCM",
    made_in: "Canada",
    game_used: false,
    purchase_price: 95,
    asking_price: 200,
    details: "Team-issued red Adirondack Flames home jersey. Blank. Size 56.",
    league: "American Hockey League",
    image_url: "https://gemmuseum.s3.us-west-2.amazonaws.com/IMG_0898.jpg",
    for_sale: true)
i2 = Item.create!(user_id: allyson.id,
    team: "Colorado Rockies",
    sport: "baseball",
    category: "jersey",
    era: "2018",
    brand: "Majestic Flexbase",
    made_in: "USA",
    game_used: true,
    purchase_price: 42,
    asking_price: 100,
    details: "Purple Rockies Spring Training jersey. Spring Training 2018 patch on right sleeve. Number 91, unknown player. Size 48.",
    league: "Major League Baseball",
    image_url: "https://gemmuseum.s3.us-west-2.amazonaws.com/IMG_0897.jpg",
    for_sale: true)
i3 = Item.create!(user_id: emily.id,
    team: "Cleveland Rockers",
    sport: "basketball",
    category: "shot glass",
    era: "late 1990s",
    brand: "none",
    made_in: "unknown",
    game_used: false,
    purchase_price: 5,
    asking_price: 10,
    details: "Tall Cleveland Rockers shot glass.",
    league: "Women's National Basketball Association",
    image_url: "https://gemmuseum.s3.us-west-2.amazonaws.com/IMG_0894.jpg",
    for_sale: false)
i4 = Item.create!(user_id: jeff.id,
    team: "Kansas City Blades",
    sport: "ice hockey",
    category: "jersey",
    era: "1990-1998",
    brand: "Bauer",
    made_in: "Canada",
    game_used: false,
    purchase_price: 35,
    asking_price: 50,
    details: "Red road Kansas City Blades (San Jose Sharks affilliate) jersey.",
    league: "International Hockey League",
    image_url: "https://gemmuseum.s3.us-west-2.amazonaws.com/IMG_0895.jpg",
    for_sale: false)
i5 = Item.create!(user_id: nathan.id,
    team: "Binghamton Devils",
    sport: "ice hockey",
    category: "jersey",
    era: "2020-2021",
    brand: "CCM",
    made_in: "Canada",
    game_used: false,
    purchase_price: 85,
    asking_price: 300,
    details: "Binghamton Devils replica jersey. This alternate style was made for the 2020-21 season but never worn. Size L.",
    league: "American Hockey League",
    image_url: "https://gemmuseum.s3.us-west-2.amazonaws.com/IMG_0917.jpg",
    for_sale: false)
    i6 = Item.create!(user_id: nick.id,
        team: "Kansas City Current",
        sport: "soccer",
        category: "scarf",
        era: "2022",
        brand: "Ruffneck",
        made_in: "Turkey",
        game_used: false,
        purchase_price: 20,
        asking_price: 25,
        details: "Kansas City Current scarf from the 2022 season, first season as the Current.",
        league: "National Women's Soccer League",
        image_url: "https://gemmuseum.s3.us-west-2.amazonaws.com/IMG_0899.jpg",
        for_sale: false)
i7 = Item.create!(user_id: allyson.id,
    team: "San Jose Stealth",
    sport: "box lacrosse",
    category: "jersey",
    era: "2006-2009",
    brand: "Reebok",
    made_in: "Canada",
    game_used: false,
    purchase_price: 50,
    asking_price: 50,
    details: "San Jose Stealth black home replica jersey. Size L.",
    league: "National Lacrosse League",
    image_url: "https://gemmuseum.s3.us-west-2.amazonaws.com/IMG_0910.jpg",
    for_sale: true)
    i8 = Item.create!(user_id: jeff.id,
        team: "Binghamton Mets",
        sport: "baseball",
        category: "hat",
        era: "1992-2016",
        brand: "New Era 59Fifty",
        made_in: "China",
        game_used: false,
        purchase_price: 10,
        asking_price: 30,
        details: "Navy Binghamton 'B-Mets' hat.",
        league: "Eastern League",
        image_url: "https://gemmuseum.s3.us-west-2.amazonaws.com/IMG_0900.jpg",
        for_sale: true)
        i9 = Item.create!(user_id: nathan.id,
            team: "St. Louis Blues",
            sport: "ice hockey",
            category: "jersey",
            era: "2017",
            brand: "Reebok Premier",
            made_in: "Indonesia",
            game_used: false,
            purchase_price: 90,
            asking_price: 70,
            details: "St. Louis Blues 2017 Winter Classic replica jersey. Size L.",
            league: "National Hockey League",
            image_url: "https://gemmuseum.s3.us-west-2.amazonaws.com/IMG_0915.jpg",
            for_sale: false)
            i10 = Item.create!(user_id: nick.id,
                team: "Kansas City Explorers",
                sport: "tennis",
                category: "jacket",
                era: "early 1990s",
                brand: "Master Apparrel Products",
                made_in: "USA",
                game_used: false,
                purchase_price: 50,
                asking_price: 500,
                details: "Kansas City Explorers varsity jacket, early logo.",
                league: "World TeamTennis",
                image_url: "https://gemmuseum.s3.us-west-2.amazonaws.com/IMG_0904.jpg",
                for_sale: false)
i11 = Item.create!(user_id: allyson.id,
    team: "St. Louis Cardinals",
    sport: "baseball",
    category: "jersey",
    era: "2013-present",
    brand: "Majestic Flexbase",
    made_in: "USA",
    game_used: true,
    purchase_price: 120,
    asking_price: 200,
    details: "St. Louis Cardinals game issued cream Saturday alternate. Size 48. Alberto Rosario, no. 68, backup catcher.",
    league: "Major League Baseball",
    image_url: "https://gemmuseum.s3.us-west-2.amazonaws.com/IMG_0912.jpg",
    for_sale: false)
    i12 = Item.create!(user_id: emily.id,
        team: "Colorado Avalanche",
        sport: "ice hockey",
        category: "puck",
        era: "2022",
        brand: "InGlasCo",
        made_in: "Canada",
        game_used: true,
        purchase_price: 60,
        asking_price: 60,
        details: "Colorado Avalanche Pride Night warmup puck used for on-ice warmups March 5 vs. Calgary.",
        league: "National Hockey League",
        image_url: "https://gemmuseum.s3.us-west-2.amazonaws.com/IMG_0918.jpg",
        for_sale: true)
        i13 = Item.create!(user_id: nick.id,
            team: "United States women's 2020 Olympic team",
            sport: "basketball",
            category: "jersey",
            era: "2020",
            brand: "Nike",
            made_in: "Thailand",
            game_used: false,
            purchase_price: 150,
            asking_price: 150,
            details: "Red Tokyo 2020 replica US Women's basketball jersey. Brittney Griner, no.15. Size XL",
            league: "Olympics",
            image_url: "https://gemmuseum.s3.us-west-2.amazonaws.com/IMG_0909.jpg",
            for_sale: false)
            i14 = Item.create!(user_id: jeff.id,
                team: "Connecticut Whale",
                sport: "ice hockey",
                category: "jersey",
                era: "2019-20",
                brand: "Prolete Sports",
                made_in: "China",
                game_used: true,
                purchase_price: 100,
                asking_price: 100,
                details: "Connecticut Whale 2019-20 home green jersey. Size L. Worn in exhibition game. Kayla Meneghin, no.3.",
                league: "Premier Hockey Federation",
                image_url: "https://gemmuseum.s3.us-west-2.amazonaws.com/IMG_0911.jpg",
                for_sale: false)
                i15 = Item.create!(user_id: nathan.id,
                    team: "Utah Starzz",
                    sport: "basketball",
                    category: "jersey",
                    era: "1997-2002",
                    brand: "Champion",
                    made_in: "Mexico",
                    game_used: false,
                    purchase_price: 42,
                    asking_price: 20,
                    details: "Utah Starzz teal script replica jersey. Debbie Black, no. 31.",
                    league: "National Hockey League",
                    image_url: "https://gemmuseum.s3.us-west-2.amazonaws.com/IMG_0908.jpg",
                    for_sale: false)

puts "seeding watches"

Watch.create!([{user_id: nick.id, item_id: i1.id}, {user_id: allyson.id, item_id:i3.id}, {user_id: emily.id, item_id: i12.id}, {user_id: nathan.id, item_id: i15.id}, {user_id: jeff.id, item_id: i8.id}, {user_id: nick.id, item_id: i6.id}, {user_id: allyson.id, item_id: i14.id}, {user_id: emily.id, item_id: i3.id}, {user_id: nathan.id, item_id: i8.id}, {user_id: jeff.id, item_id: i10.id}])

puts "seeding complete, happy collecting!"